### ISSUE TITLE
Copy short URL to clipboard

### ISSUE THREAD

**Issue by merchako** [caleb531/youversion-suggest-alfred#15]
I would love to have a way to get short URLs onto my clipboard through Alfred. I volunteer as a social media host for our streaming services, and I need to quickly give our congregation links to verses in the Bible app. I have made some small changes in my copy of your workflow to make this work, but it's a bit of a hack. You might be interested in making it work in a more rigorous, less buggy way.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/441789/102720938-fb293a00-42bc-11eb-9476-dfa12c5958da.png">

I added a Copy to Clipboard node with the content "`{var:ref_url}`" that works when the <kbd>alt</kbd> modifier is added. 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/441789/102720379-8c96ad00-42b9-11eb-8287-22776130a1b2.png">

I also changed the URL template at _yvs/core.py:25_ to use a shorter version of the URL that still dependably works.

```
# The template used to build the URL for a Bible reference
# REF_URL_TEMPLATE = 'https://www.bible.com/bible/{ref}'
REF_URL_TEMPLATE = 'bible.com/{ref}' # Added by Alex Mercado for shorter URLs on 20 Dec 2020
```

Of course, my URL template is surely less stable than yours, but it helps so much when I have character limits. Perhaps you'd want to make this a switch that users can set. I'd love to hear your thoughts. Thank you for your excellent contribution to the Kingdom!

Aside: I use a different keyword "bible", instead of your standard "yv", just because my brain has a hard time invoking "yv" when I need it.

**Comment by caleb531** [comment]
@merchako

I can't make any promises, but I will consider adding a preference for enabling a shorter reference URL in the future! For the time being, though, I see no issue with your solution from a stability perspective. I've actually helped a handful of my users tweak the workflow to fit their needs.

**Comment by merchako** [comment]
Well that didn't take long to break! The short `REF_URL_TEMPLATE = 'bible.com/{ref}'` I used doesn't work anymore because it's missing the protocol `https://`. When I add that back,  resulting in `https://bible.com/{ref})`, it works fine.

What caused the change? I'm not sure. I upgraded to Big Sur recently. Maybe it was that, or maybe it was a consequent update to Alfred.

I would love to have the even shorter version back because those few characters make a different in social media posts. Let me know if you come across a workaround.

**Comment by caleb531** [comment]
@merchako You might be able to "cheat" a little by prepending the protocol in the **Open URL** object that's part of the workflow. See my attached screenshot.

![Screen Shot 2021-01-04 at 7 01 43 PM](https://user-images.githubusercontent.com/872474/103601813-52372d80-4ebf-11eb-9bcf-a2c92f8f7c55.png)

**Comment by merchako** [comment]
Thanks for the tip! This helped me open it in the browser correctly, but to make _Copy Content to Clipboard_ work, I also had to change a line in _copy_ref.py_.

```python
# Retrieves HTML for of the chapter to which the reference belongs
def get_chapter_html(ref):

    chapter_uid = get_ref_chapter_uid(ref)
    # url = core.get_ref_url(ref_uid=chapter_uid)
    # Updated by Alex Mercado on 6 Jan 2020
    url = "https://" + core.get_ref_url(ref_uid=chapter_uid)
```

**Comment by caleb531** [comment]
@merchako That's good to know, and glad it's working for you! I will be closing this issue since you found a suitable workaround.
