### ISSUE TITLE
Add support for Turkish / Türkçe - tur

### ISSUE THREAD

**Issue by kenanmike** [caleb531/youversion-suggest-alfred#16]
Hi Caleb,

Thanks for your wonderful workflow. Is it possible for you to add support for Turkish? It would be a huge asset to me. Thank you!

**Comment by caleb531** [comment]
@kenanmike Thanks for the request—I will work on this! Can you please let me know what translation I should use as the default Turkish translation? Please see the link below for a list of translations that YouVersion supports:
https://www.bible.com/languages/tur

**Comment by kenanmike** [comment]
Thanks! By far the most used one here is the Kutsal Kitap Yeni Çeviri 2001, 2008 (TCL02)

On 4 Apr 2022, at 20:13, Caleb Evans ***@***.***> wrote:

﻿

@kenanmike<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkenanmike&data=04%7C01%7C%7C2482973a60094d4cb97b08da165e6dee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637846892064371500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dPZh8V%2BEW1IiXspaj5tfByJTCWgmZ8TdONkev0GhcJc%3D&reserved=0> Thanks for the request—I will work on this! Can you please let me know what translation I should use as the default Turkish translation? Please see the link below for a list of translations that YouVersion supports:
https://www.bible.com/languages/tur<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.bible.com%2Flanguages%2Ftur&data=04%7C01%7C%7C2482973a60094d4cb97b08da165e6dee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637846892064371500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JmXjHbY5Us1xblfTMgHSnNsxNZbEZ39giwMWN56hHgA%3D&reserved=0>

**Comment by caleb531** [comment]
@kenanmike Alright, I just released YouVersion Suggest v12.1.0 with Turkish Bible support! You can download the new workflow here, then you can run`yvset language Türkçe` to set it:

https://github.com/caleb531/youversion-suggest-alfred/releases/tag/v12.1.0

**Comment by kenanmike** [comment]
That was very quick! Done and done...and working like a charm now.

**Comment by caleb531** [comment]
@kenanmike My pleasure! Glad it's working for you. 🙂

Blessings,
Caleb
