### ISSUE TITLE
Enhancement: Add paste option

### ISSUE THREAD

**Issue by kenanmike** [caleb531/youversion-suggest-alfred#17]
Can you add a paste option? I'd like the default when I press enter not to be going to the Youversion website but to immediately paste the text (not just ref.) into whatever application I'm using without having to copy it first and then paste it in a separate action. But maybe going to the Youversion website could be one of the other keystrokes like Shift + Enter, or Fn + Enter.

P.S. To be able to use it with multiple languages, I duplicated the workflow and changed the keywords so they can work alongside each other. I also added hotkeys so I can rapidly go straight to references. I love this workflow so much – thank you!

**Comment by bevanjkay** [comment]
When editing the workflow double click on the "copy to clipboard" option and tick "automatically paste to front-most app".

![Screen Shot 2022-04-05 at 4 10 58 pm](https://user-images.githubusercontent.com/40621599/161690223-99bfa919-f0c9-4b5c-876f-e9ea2c5e658c.png)

In the `yvset` command you can set copy to be the default, and open in browser to require holding command.

**Comment by kenanmike** [comment]
Ah yes, it's working with paste now. Thank you for your grace & patience!

**Comment by kenanmike** [comment]
My final issue for today is that duplicating the workflow doesn't seem to allow for multiple languages, as updating the language on one then changes the default language for the other workflow as well. Any possible support for using Turkish & English for example?

**Comment by bevanjkay** [comment]
@kenanmike It is an interesting thought though for it to be configurable.

@caleb531 Thoughts on adding another variable that has the copy to clipboard/copy and paste baked into `yvset`?


> My final issue for today is that duplicating the workflow doesn't seem to allow for multiple languages, as updating the language on one then changes the default language for the other workflow as well. Any possible support for using Turkish & English for example?

The preferences are stored globally for the workflow at present, so they will be the same across both/all instances.

**Comment by caleb531** [comment]
@kenanmike 

>My final issue for today is that duplicating the workflow doesn't seem to allow for multiple languages, as updating the language on one then changes the default language for the other workflow as well. Any possible support for using Turkish & English for example?

You need to change the bundle ID in the workflow settings (double-click the workflow in the Workflows list), AND update the `WORKFLOW_UID` variable in `yvs/core.py`. Please see my attached screenshots.

![Screen Shot 2022-04-05 at 11 21 53 AM](https://user-images.githubusercontent.com/872474/161823839-cda2c542-7c79-4238-9763-d1943235f04a.png)
![Screen Shot 2022-04-05 at 11 22 06 AM](https://user-images.githubusercontent.com/872474/161823865-72db2fee-794c-4595-8687-82d88956b8e4.png)
![Screen Shot 2022-04-05 at 11 22 29 AM](https://user-images.githubusercontent.com/872474/161823878-09027e71-f4d5-438a-b712-958876426619.png)

**Comment by caleb531** [comment]
@kenanmike Unfortunately, there's no good way to update the workflow to the latest version while keeping these customizations intact. I will add to my list the request for adding a Paste-by-Default preference, however I cannot provide a timeline of when I can get to it.

Fortunately, @bevanjkay's workaround is by far the simplest and most easily replicable solution for now.

**Comment by caleb531** [comment]
@kenanmike Unless you have any further comment, I think it's safe to close this issue.
