### ISSUE TITLE
Suggestion / Feature Request: W Reference View, Display verses in Alfred Window like in the Search View

### ISSUE THREAD

**Issue by kenanmike** [caleb531/youversion-suggest-alfred#18]
When I use the Reference View ("Type the Name...") it only shows the reference I've already typed:
![image](https://user-images.githubusercontent.com/85374001/161980051-3b3337ee-9c6d-45ad-9c2c-c01afb0c90cf.png)

But what is more useful to me when I've typed the reference is for the text to also appear there, just like it does in the Search View. But the Search view won't display the text if you search the reference. Showing the text in this way would mean I can see the text before deciding to open a new webpage (Youversion) or copying something I'm not sure is the verse I'm looking for. 
![image](https://user-images.githubusercontent.com/85374001/161981682-51b8420e-7467-476b-9569-fc22d0072222.png)

Extra possibility: when you search a chapter, could this Workflow list each verse in order as Alfred Selection options, similarly to how the Search View lists verses?  So when I search Gen 2, it lists all the verses in order, and if I hit ⌘2 it will copy verse 2, whereas if I hit ⌘7 it will copy verse 7 (or open the Youversion page if you've chosen that setting).

![image](https://user-images.githubusercontent.com/85374001/161981825-1250c6ae-32d3-4c17-aea8-5593b84a6d40.png)

**Comment by caleb531** [comment]
@kenanmike Thank you for the feature suggestion! This was actually a design decision of mine, for the sake of performance. To do what you're suggesting would slow down the Filter keyword significantly, as I would need to fetch it for every single reference result in the list.

What I do instead is press the _Shift_ key once when over a result, a Quick View popup of the reference webpage in a browser will appear. Pressing the _Shift_ key again will dismiss the Quick View popup.

![Screen Shot 2022-04-07 at 12 44 24 PM](https://user-images.githubusercontent.com/872474/162283799-fdac5fb5-13d2-4f90-a5a6-12836b2aa886.png)

**Comment by kenanmike** [comment]
That makes sense, thanks for explaining the rationale. I wonder, is it possible to display just one verse each time then? The problem with the Shift option is it takes an age load the Quick View which defeats the point, and also it create a separate dialogue which you have to close to get back to the Alfred Window. The ESV Alfred workflow displays the just one verse (either the ref you typed, or if a chapter, just the first verse of the chapter). This seems significantly preferable and shouldn’t affect speed given it’s only seizing one verse. What do you think?

**Comment by caleb531** [comment]
@kenanmike You should already be able use the Search filter (`bibsearch`, in your case) to type in the reference you're looking for, which should show as the first result with the first line of content. For example:

![Screen Shot 2022-04-07 at 2 39 43 PM](https://user-images.githubusercontent.com/872474/162324423-a28ca4f9-416e-4f3f-9413-4418c8eee729.png)

So in a way, you can disregard `bibfilter` and just use `bibsearch` for everything. Is that more in line with what you are looking for?

**Comment by kenanmike** [comment]
Understood. I actually thought the search view couldn't use references but I think it just has different reference search behaviours. Is it possible to bring the search view behaviours more in line with the reference view so when I search ps 150-1 it behaves more like the reference view? E.g. the top screenshot is what comes up with the standard reference view, but then the next two are from the search view which doesn’t produce the correct verse:

**Comment by caleb531** [comment]
@kenanmike That can be tricky because it opens up the potential for ambiguous queries. For example, I may start typing `m` with the intent of searching for a verse in the book of Matthew. However, I may _also_ type `m` to search for `messiah` or `mothers`. So the app wouldn't know which "mode" to be in until you've fully typed out a book name and chapter+verse.

**Comment by caleb531** [comment]
@kenanmike After having this issue open for just about two years, I think I am going to close it now, since I do not plan on merging `yvfilter` and `yvsearch`.
