### ISSUE TITLE
great app god must bless

### ISSUE THREAD

**Issue by benjaminhsu20021009** [caleb531/youversion-suggest-alfred#20]
hope to add recovery version in the future!

**Comment by caleb531** [comment]
Hi, @benjaminhsu20021009! Can you please clarify what you mean by a "recovery version"?

**Comment by caleb531** [comment]
@benjaminhsu20021009 Just wanted to check in if you could please provide more detail about what you are looking for in this functionality.

**Comment by benjaminhsu20021009** [comment]
sorry for being too late to reply, the "recovery version" I mean is a version of bible just like ESV or AMP

**Comment by caleb531** [comment]
@benjaminhsu20021009 YouVersion Suggest already supports multiple versions/translations, if that's what you're wondering. You can use the `yvset version` command to change your preferred version/translation.
