### ISSUE TITLE
Alfred shortcut does not complete the search

### ISSUE THREAD

**Issue by Shl1ck** [caleb531/youversion-suggest-alfred#22]
What version of YouVersion Suggest were you using?
13.0.1
What were you doing?
using Alfred 5.0.1 I would type the appropriate shortcut  e.g. yvfilter, upset etc. in place with a view to adding the verses desired.
What did you expect to happen?
I expected to see yvf expand to yvfilter (as used to happen in Alfred 4)) and then, when I would write a bible text in place (as I have done so for several years), the Bible verse would remain on view in Alfred. 
What happened instead?
the yvf expanded to yvfilter (etc etc) but when I added the bible text the search box switched to search google (etc) for "yvfilter Matthew 3:1-6"
I have python on my M1 MacBook Air 13, at least I can see "python launcher" and it is active in activity monitor. 
Any help much appreciated.
Stephen

**Comment by caleb531** [comment]
Hi Stephen,

Did you recently upgrade to macOS Ventura? If so, please see my tweet about this. The trick is upgrading Apple's Command Line Tools via:

xcode-select --install

Regards,
Caleb

**Comment by Shl1ck** [comment]
I tried performing the relevant command but it announced that it cannot install the software.
The following error appears in the debugging screen 

ERROR: YouVersion Suggest[Script Filter] Code 1: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

There is no "Developer" folder in my Library. Maybe that is the problem??

**Comment by caleb531** [comment]
@Shl1ck Hmm, try running:

```sh
sudo xcode-select --switch /Library/Developer/CommandLineTools
```

And then run:

```sh
xcode-select --install
```

**Comment by Shl1ck** [comment]
Hi Caleb

Thank you for your care in helping me solve this mystery

Not being a clear-thinking tech guy, I know that the shortcut is now working, but I am not sure what exactly started it again. It was after continued attempts to follow the previous email’s instructions. But without any sense that I had been able to follow them.

Great to have guys with your skills coaching us all.

Stephen

**Comment by caleb531** [comment]
@Shl1ck My pleasure! Glad it resolved itself, even mysteriously. Maybe it's a Holy Spirit thing. 😉 🤷‍♂️

**Comment by caleb531** [comment]
@Shl1ck Closing this issue now that this has been resolved for a week or two.
