### ISSUE TITLE
yvsearch command returning no results

### ISSUE THREAD

**Issue by caleb531** [caleb531/youversion-suggest-alfred#24]
Per @BPontevorvo's report via https://github.com/caleb531/youversion-suggest-alfred/issues/23#issuecomment-1483814739:

> Now I have an issue where a search that should return a value is not. Picture below!
> 
> ![227717877-66cb37e6-c41d-41fe-a011-4b48d9d015ed](https://user-images.githubusercontent.com/872474/227732512-dc5bab95-df99-4e16-88da-025d023145fe.png)

I am able to reproduce the issue on my end. It looks like YouVersion has changed the HTML markup on their search result pages significantly ([link](https://www.bible.com/search/bible?query=without%20faith)), so the workflow isn't able to find the results anymore.

I will work on fixing this immediately.

**Please note:** this issue only affects the `yvsearch` command; the `yvfilter` command (for looking up Bible chapters/verses by name) still works like a charm.

**Comment by caleb531** [comment]
## Status Update 3/26

The fix is coming along very well, and will be released as part of the upcoming v14 release within the next few days.

If you are in need of this fix immediately, then you are welcome to try the attached beta build. It should be actually pretty stable, since all automated tests are passing—it just lacks my official seal of completeness.

[YouVersion Suggest 14.0.0-beta.1 (Alfred 5).alfredworkflow.zip](https://github.com/caleb531/youversion-suggest-alfred/files/11073372/YouVersion.Suggest.14.0.0-beta.1.Alfred.5.alfredworkflow.zip)

**Comment by caleb531** [comment]
## Status Update 3/27

After much development and testing, I am pleased to announce that the fix for this issue is now available in the officially-released v14.0.0 release. Check it out here:
https://github.com/caleb531/youversion-suggest-alfred/releases/tag/v14.0.0

**Comment by caleb531** [comment]
## Status Update 3/27

After much development and testing, I am pleased to announce that the fix for this issue is now available in the officially-released v14.0.0 release. Check it out here:
https://github.com/caleb531/youversion-suggest-alfred/releases/tag/v14.0.0

cc @BPontevorvo

**Comment by BPontevorvo** [comment]
@caleb531 - Thank you so much for this. It is so nice to have this up and running again. Much appreciated! Love this tool

**Comment by caleb531** [comment]
@BPontevorvo Great! And thank you for the kind words! Also closing this issue now since v14 has been released for a bit.

Although I was just recently informed of another issue related to copying verses to the clipboard. You can follow #25 for updates there (I actually have a fix ready and will be attaching a beta version of the workflow in a few minutes).
