### ISSUE TITLE
Add support for indonesian bible (terjemahan baru)

### ISSUE THREAD

**Issue by situmorang-com** [caleb531/youversion-suggest-alfred#8]
Dear Caleb531,
Do you mind adding support for indonesian bible (terjemahan baru)?

Thanks.

**Comment by caleb531** [comment]
@situmorang-com Absolutely! To confirm, are you referring to "Bahasa Indonesia - Indonesian"? (from [the official list of supported YouVersion languages](https://my.bible.com/languages), the second in the list with the code `ind`?)

If that's not the correct language, let me know. But if so, could you please also specify which version I should set as the default version? Choices are TSI, TB, BIMK, and AMD ([the list is here](https://my.bible.com/languages/ind)).

**Comment by situmorang-com** [comment]
Hi caleb thanks so much...yes...the indonesian version i was referring to is TB (Terjemahan Baru)


________________________________

**Comment by caleb531** [comment]
@situmorang-com I am please to announce that I have officially released YouVersion Suggest v9.1.0 with support for Bahasa Indonesia. The default version is BIMK; I hope this is to your liking, but do know that you can change it using the `yvset language` command.

I am closing this issue unless you have anything further to comment or request.

**Comment by caleb531** [comment]
@situmorang-com Hi, I just wanted to check in: were you able to download the new version with Indonesian support? The link is below if you haven't yet:

https://github.com/caleb531/youversion-suggest-alfred/blob/master/YouVersion%20Suggest%20(Alfred%203).alfredworkflow?raw=true

**Comment by caleb531** [comment]
@situmorang-com My apologies; I completely missed that you requested TB as the default version, not BIMK. I will push out an update today with that fix.

But as I said, if you've already installed the current version, you can use `yvset version tb` to set your preferred version.

**Comment by caleb531** [comment]
@situmorang-com Done! Below is the link to YouVersion Suggest v9.1.1, where TB is now the default version for Indonesian:

https://github.com/caleb531/youversion-suggest-alfred/raw/master/YouVersion%20Suggest%20(Alfred%203).alfredworkflow
