### ISSUE TITLE
Largetype the verse

### ISSUE THREAD

**Issue by spencerclrk** [caleb531/youversion-suggest-alfred#9]
Love this workflow. Is there a way to change what gets interpreted as the Largetype? I'd like to send the verse instead of the reference.

**Comment by spencerclrk** [comment]
In case anyone is curious, here is a solution:

1. Copy the `Copy Reference` script
2. Link it to the two script filters with a key of your choice
3. Add a “Large Type” to the output of `Copy Reference`

![screen shot 2018-09-25 at 11 08 26 pm](https://user-images.githubusercontent.com/10419624/46055058-1de93a00-c118-11e8-92a5-d56aff36456c.png)

![screen shot 2018-09-25 at 11 12 05 pm](https://user-images.githubusercontent.com/10419624/46055118-702a5b00-c118-11e8-8842-3f1cf683eb65.png)

**Comment by caleb531** [comment]
@spencerclrk This is a great idea. I make no promises, but I will at least consider this for a future release. In the meantime, I'm glad you found a workaround.

**Comment by Fragensteller** [comment]
I would highly appreciate this enhancement.
It was possible in the ESV workflow (http://www.packal.org/workflow/esv-online-bible) and I used it a lot.
It is an easy way to project a verse or to read a verse (or multiple verses) without having to look it up online or pasting it somewhere.
The solution suggested by ghost doesn't work for me, dk why.

Thank you so much for your work! I love this workflow.

**Comment by caleb531** [comment]
@Fragensteller The solution that works with the latest release is to press the _Shift_ key (or press `cmd-y`) when a result is selected to trigger the Quick Look view. This will pop open the YouVersion webpage with that verse/passage for you to read. This is the way I have always done it, and I think it works pretty well.

<img width="1034" alt="Screenshot 2023-01-21 at 10 35 36 AM" src="https://user-images.githubusercontent.com/872474/213882016-ab724b1f-6558-4f6d-8767-c1bda96aa246.png">
